import numpy as np
import pandas as pd
from typing import Dict

class MonteCarloEngine:
    """
    Vectorized Monte Carlo engine for simulating future price bounds using
    the advanced forecasted volatility generated by the GARCH-NN hybrid engine.
    """
    def __init__(self, simulations: int = 1000, horizon_days: int = 21):
        self.simulations = simulations
        self.horizon_days = horizon_days

    def simulate_gbm(self, current_price: float, daily_volatility: float, drift: float) -> np.ndarray:
        """
        Executes a Geometric Brownian Motion (GBM) simulation matrix.
        Returns matrix of shape (horizon_days, simulations).
        """
        # Generate random standard normal variables for shocks
        Z = np.random.standard_normal((self.horizon_days, self.simulations))
        
        # Calculate daily drift and diffusion components
        # GBM formula: S_t = S_t-1 * exp((mu - 0.5 * sigma^2)*dt + sigma*sqrt(dt)*Z)
        daily_drift = drift - 0.5 * (daily_volatility ** 2)
        daily_diffusion = daily_volatility * Z
        
        # Calculate price pathways incrementally
        daily_log_returns = daily_drift + daily_diffusion
        
        # Convert to prices
        price_paths = np.zeros_like(daily_log_returns)
        price_paths[0] = current_price * np.exp(daily_log_returns[0])
        
        for t in range(1, self.horizon_days):
            price_paths[t] = price_paths[t-1] * np.exp(daily_log_returns[t])
            
        return price_paths

    def get_risk_metrics(self, price_paths: np.ndarray) -> Dict[str, float]:
        """
        Extracts percentiles from the final day of the simulated paths.
        """
        terminal_prices = price_paths[-1, :]
        return {
            "Worst Expected (5th Pct)": np.percentile(terminal_prices, 5),
            "Median Expected (50th Pct)": np.percentile(terminal_prices, 50),
            "Best Expected (95th Pct)": np.percentile(terminal_prices, 95),
            "Mean Expected": np.mean(terminal_prices)
        }
